development:
  clients:
    default:
      database: demo-events-development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: demo-events-test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: mongodb+srv://juansleonc:qwerty123@cluster0.d6qraru.mongodb.net/demo-events-production?retryWrites=true&w=majority
  options:
    use_activesupport_time_zone: true
    log_level: :warn
