version: '5'

services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    network_mode: "host"

  auth:
    build: ./auth
    image: auth-demo-events:latest
    volumes:
      - ./auth:/app
    depends_on:
      - db
    network_mode: "host"
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: 7c1a0780566509058bf1824028c60780c860ea848f747456748ee9d0631dcc68145f6f78a6ecb8076012b136f569b224c532def2100515fe56844e09e6a2b018

  events:
    build: ./events
    image: events-demo-events:latest
    volumes:
      - ./events:/app
    depends_on:
      - db
    network_mode: "host"
    environment:
      RAILS_ENV: development
      SECRET_KEY_BASE: 7c1a0780566509058bf1824028c60780c860ea848f747456748ee9d0631dcc68145f6f78a6ecb8076012b136f569b224c532def2100515fe56844e09e6a2b018
    
volumes:
  mongodata:

networks:
  backend:
